name: Atualizar Subm贸dulo em MovieStarMain

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-submodule:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checar o reposit贸rio atual
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAIN_REPO_TOKEN }}
          submodules: true
          persist-credentials: false

      - name: Configurar Git e atualizar subm贸dulo
        env:
          TOKEN: ${{ secrets.MAIN_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${TOKEN}@github.com/StarDev-Solutions/MovieStarMain.git main-repo
          cd main-repo

          git config submodule.frontend.url https://x-access-token:${TOKEN}@github.com/StarDev-Solutions/MovieStarFrontend.git
          git submodule update --init --recursive

          cd frontend
          git fetch origin
          git checkout main
          git pull origin main
          cd ..

          git add frontend
          git commit -m "Atualizando subm贸dulo frontend automaticamente via GitHub Actions" || echo "Nada para commitar"
          git push origin main
